### ISSUE TITLE
Custom Validator won't show error message unless in debug mode

### ISSUE THREAD

**Issue by rcady** [aydus/Addressvalidator#11]
When I return my return data as a string message it doesn't pop up a warning for the customer unless Address Validator is in Debug Mode. The problem with this is that it continues like the address is valid, but it's not.

Here's the portion of my `_processResponse` function:
```
if (preg_match("/p\.* *o\.*/i", $this->_address->getStreet1()) || preg_match("/p\.* *o\.*/i", $this->_address->getStreet2())
    && $this->_address->getAddressType() === 'shipping'){
    $return['error'] = false;
    $return['data'] = Mage::helper('addressvalidator')->getMessaging('po_box_error');
    return $return;
}
```

It works fine in debug mode, but it just won't return anything in production mode.

is there something else I should be looking at?

**Comment by rcady** [comment]
I did find a work around for this issue. Since I'm just checking to see if the address is a PO Box, I can just add a helper function to check that and return the observer with the error data and display it to the customer.

I'm not sure if there is another way to return the error to the customer.

**Comment by ExtensionsStore** [comment]
Try it with:

`$return['error'] = true;
`

**Comment by ExtensionsStore** [comment]
Sorry Ryan, I meant to look into this but have been swamped. I'll look into this weekend if you still are having issues.

**Comment by rcady** [comment]
Thanks for the reply! I'm pretty sure I solved this particular issue. Sorry for not replying sooner!
